NUM_CLIENTS = 4
NUM_ROUTERS = 2
NUM_SERVERS = 2

SIMULATION_TIME = 10.0

CLIENT_ROUTER_RATE = "100Mbps"
CLIENT_ROUTER_DELAY = "2ms"

BOTTLENECK_RATE = "10Mbps"
BOTTLENECK_DELAY = "20ms"

ROUTER_SERVER_RATE = "100Mbps"
ROUTER_SERVER_DELAY = "2ms"

# Initial traffic settings
UDP_RATE = "2Mbps"
UDP_PACKET_SIZE = 1024  # bytes
UDP_PORT = 5000

TCP_PORT = 5001
